server:
  port: 9998

spring:
  application:
    name: pet-life

  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.187.217:3306/pet_life?characterEncoding=utf8&useSSL=false
    username: pet
    password: petpetpet

  # redis 配置
  redis:
    host: 127.0.0.1
    pool:
      max-active: 300
      max-idle: 300
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 30000

  # 修改spring匹配规则 兼容Swagger2
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

wechat:
  # 微信小程序
  applet:
    app-id: wx04bf50bd25925567
    app-secret: 73573a0019739716c0fb7ae238c97dd8
    access-token-api-url: https://api.weixin.qq.com/sns/jscode2session

translation:
  predict:
    url: http://39.105.187.217:8101/predict